project 'proto-application.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proto-application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for proto-application
  pod 'OAuthSwift', '~> 1.2.0'
end
