project 'proto-application.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'proto-application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  
  # Pods for proto-application
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'
  pod 'KeychainSwift', '~> 13.0'
  pod 'FSCalendar'
  pod 'Down'
  #pod 'Starscream', '~> 3.1.0'
  #pod 'Socket.IO-Client-Swift', '~> 15.0.0'
  
end