project 'proto-application.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'proto-application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  
  # Pods for proto-application
  pod 'OAuthSwift', '~> 1.2.0'
  pod 'Alamofire', '~> 4.7'
  
end